language: rust
cache: cargo
script:
  - cd holysee
  - cargo build --verbose --all
  - cargo test --verbose --all
rust:
  - stable
  - beta
  - nightly
notifications:
  irc:
    channels:
      - "chat.freenode.net##tapiri"
    on_success: always
    on_failure: always
    use_notice: true
