language: rust
cache: cargo
script:
  - cd holysee
  - cargo build --verbose --all
  - cargo test --verbose --all
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
notifications:
  irc:
    channels:
      - "chat.freenode.net##altri"
      - "chat.freenode.net##holysee"
    on_success: always # default: always
    on_failure: always # default: always
    use_notice: true
