debug = true

[irc]
nickname = "user"
username = "username"
real_name = "holysee bot"
password = "password"
host = "irc.freenode.net"
port = "6697"
channel = "#example"
ssl = true
ssl_verify = truedebug = true

[telegram]
token = "apikey"
chat_id = "012345"
