[package]
name = "holygram"
version = "0.1.0"
authors = ["Bigo <bigo@crisidev.org>, Uovobw <uovobw@gmail.com"]

[dependencies]
config = "0.6"
serde = "1.0.17"
serde_derive = "1.0.17"
log = "0.3.8"
pretty_env_logger = "0.1.1"
telebot = "0.1.1"
tokio-core = "0.1.10"
futures = "0.1.17"
